---
title: "Transferring Presidents"
author: "Ludvig Olsen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Transferring Presidents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r}
library(transfrr)
library(dplyr)
library(knitr)
library(lubridate)
library(ggplot2)
```

# Data
sunspots_ stems from https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/sunspot.month.html
But with added year and month variables.
1749-2012
Monthly numbers of sunspots, as from the World Data Center, aka SIDC.

USA.presidents
Modified version of the dataset found at
http://thedatahub.org/api/data/ba0cdb03-c0f0-45ff-a21f-63fdf6ce1a89/
License is public domain
Upto and containing Obama.

```{r}
sunspots <- sunspots_
presidents <- USA.presidents

sunspots %>% head(5) %>% kable()
presidents %>% head(5) %>% kable()
```

# Transferring presidents to the right years

```{r}
transferred <- sunspots %>% 
  transfer(presidents, by = c("start_date", "took_office"))

ggplot(transferred, aes(start_date, sunspots)) +
  geom_point() +
  geom_smooth()

ggplot(transferred, aes(president, sunspots)) +
  geom_violin() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

